import type { TranslationDictionary } from "./types";

export const ar: TranslationDictionary = {

  "app.name":"CreatorOS Enterprise",

  "navigation.commandCenter":"مركز القيادة",
  "navigation.intelligence":"الذكاء",

  "navigation.dashboard":"لوحة التحكم",
  "navigation.projects":"المشاريع",
  "navigation.scripts":"السكربتات",
  "navigation.calendar":"تقويم المحتوى",
  "navigation.aiStudio":"استوديو الذكاء الاصطناعي",
  "navigation.prompts":"مكتبة القوالب",

"dashboard.active":"النشطة",

"dashboard.totalWorkspaces":"إجمالي مساحات عمل المحتوى",
"dashboard.scriptsStored":"السكربتات المخزنة على الخادم",
"dashboard.productionAssets":"أصول الإنتاج",

"dashboard.scheduledContent":"المحتوى المجدول",
"dashboard.calendarItems":"عناصر تقويم النشر",
"dashboard.calendarPipeline":"مسار النشر",

"dashboard.aiPrompts":"قوالب الذكاء الاصطناعي",
"dashboard.promptTemplates":"قوالب ذكية قابلة لإعادة الاستخدام",
"dashboard.aiWorkspace":"مساحة عمل الذكاء الاصطناعي",

"dashboard.productionOverview":"نظرة عامة على الإنتاج",
"dashboard.workspaceDistribution":"توزيع مساحة العمل",
"dashboard.recentActivity":"النشاط الأخير",
"dashboard.latestItems":"آخر عناصر مساحة العمل",
"dashboard.systemStatus":"حالة النظام",

  "navigation.expand":"توسيع القائمة",
  "navigation.collapse":"طي القائمة",
  "navigation.aria":"التنقل داخل CreatorOS",

  "system.operational":"النظام يعمل",
  "system.disconnected":"النظام غير متصل",
  "system.connected":"الواجهة والخادم متصلان",
  "system.backendUnavailable":"الخادم غير متاح",

"navigation.open":"فتح القائمة",

"header.search":"ابحث في CreatorOS...",
"header.production":"الإنتاج",
"header.refresh":"تحديث لوحة التحكم",
"header.admin":"مسؤول مساحة العمل",

  "dashboard.title":"مركز قيادة CreatorOS",
  "dashboard.subtitle":"إدارة المشاريع والإنتاج والنشر والذكاء الاصطناعي من مكان واحد.",

  "actions.newProject":"مشروع جديد",
  "actions.newScript":"سكربت جديد",
  "actions.schedule":"جدولة المحتوى",
  "actions.newPrompt":"قالب ذكي جديد",

"quickActions.title":"إجراءات سريعة",
"quickActions.subtitle":"ابدأ الإنشاء",

"quickActions.createProject":"إنشاء مشروع",
"quickActions.startWorkspace":"بدء مساحة عمل محتوى جديدة",

"quickActions.createScript":"إنشاء سكربت",
"quickActions.addScript":"إضافة سكربت إلى مشروع",

"quickActions.scheduleContent":"جدولة المحتوى",
"quickActions.addPublishDate":"إضافة تاريخ نشر",

"quickActions.createPrompt":"إنشاء قالب ذكاء اصطناعي",
"quickActions.saveTemplate":"حفظ قالب ذكي",

"dashboard.operationalHealth":"الصحة التشغيلية",

"dashboard.backendApi":"واجهة الخادم",
"dashboard.storage":"التخزين",

"dashboard.healthy":"سليم",
"dashboard.attention":"يحتاج إلى انتباه",
"dashboard.operational":"يعمل",

"projects.workspace":"مساحة عمل المشاريع",
"projects.title":"مشاريع المحتوى",
"projects.subtitle":"تنظيم والبحث وإدارة جميع مساحات إنتاج CreatorOS من واجهة تشغيل واحدة.",
"projects.total":"إجمالي المشاريع",
"projects.visible":"النتائج الظاهرة",

"projects.search":"بحث في المشاريع...",
"projects.filterPlatform":"تصفية حسب المنصة",
"projects.allPlatforms":"كل المنصات",
"projects.filterStatus":"تصفية حسب الحالة",
"projects.allStatuses":"كل الحالات",
"projects.table":"جدول",
"projects.kanban":"كانبان",

"projects.noProjects":"لا توجد مشاريع",
"projects.adjustFilters":"قم بتعديل الفلاتر أو أنشئ مشروعًا جديدًا.",

"projects.project":"المشروع",
"projects.platform":"المنصة",
"projects.status":"الحالة",
"projects.id":"المعرف",
"projects.actions":"الإجراءات",

"projects.creatorProject":"مشروع CreatorOS",
"projects.updateStatus":"تحديث الحالة",
"projects.delete":"حذف",
"projects.update":"تحديث",
"projects.details":"تفاصيل المشروع",
"projects.deleteProject":"حذف المشروع",

"scripts.workspace":"مساحة عمل السكربتات",
"scripts.title":"سكربتات الإنتاج",
"scripts.subtitle":"كتابة ومراجعة وإدارة جميع سكربتات CreatorOS من بيئة إنتاج مركزة.",
"scripts.total":"إجمالي السكربتات",
"scripts.availableProjects":"المشاريع المتاحة",

"scripts.library":"مكتبة السكربتات",
"scripts.allScripts":"جميع السكربتات",

"scripts.search":"بحث في السكربتات...",
"scripts.filterStatus":"تصفية السكربتات حسب الحالة",
"scripts.allStatuses":"كل الحالات",

"scripts.noScripts":"لا توجد سكربتات",
"scripts.changeFilters":"أنشئ سكربتًا أو غيّر الفلاتر الحالية.",

"scripts.selectToView":"اختر سكربتًا لعرض معلوماته.",
"scripts.details":"تفاصيل السكربت",
"scripts.information":"المعلومات",
"scripts.status":"الحالة",
"scripts.versionHistory":"سجل الإصدارات",
"scripts.currentVersion":"الإصدار الحالي",
"scripts.currentServerVersion":"إصدار السيرفر الحالي",
"scripts.loadedBackend":"تم التحميل من خادم CreatorOS الخلفي",

  "calendar.workspace":"تقويم المحتوى",
  "calendar.title":"عمليات النشر",
  "calendar.subtitle":"خطط وافحص ونظم محتوى CreatorOS المجدول عبر المشاريع والمنصات.",
  "calendar.totalItems":"إجمالي العناصر",
  "calendar.scheduled":"المجدول",
  "calendar.withoutDate":"بدون تاريخ",
  "calendar.currentPeriod":"الفترة الحالية",
  "calendar.today":"اليوم",
  "calendar.search":"بحث في المحتوى المجدول...",
  "calendar.filterProject":"تصفية حسب المشروع",
  "calendar.allProjects":"كل المشاريع",
  "calendar.filterStatus":"تصفية حسب الحالة",
  "calendar.allStatuses":"كل الحالات",
  "calendar.filterPlatform":"تصفية حسب المنصة",
  "calendar.allPlatforms":"كل المنصات",
  "calendar.view.month":"شهر",
  "calendar.view.week":"أسبوع",
  "calendar.view.day":"يوم",
  "calendar.view.timeline":"الخط الزمني",
  "calendar.scheduleContent":"جدولة محتوى",
  "calendar.publishingQueue":"قائمة انتظار النشر",
  "calendar.upcomingContent":"المحتوى القادم",
  "calendar.queueEmpty":"قائمة النشر فارغة",
  "calendar.queueEmptyDescription":"لا يوجد محتوى مجدول ضمن الفلاتر الحالية.",
  "calendar.noDate":"بدون تاريخ",
  "calendar.aiSuggestions":"اقتراحات الجدولة الذكية",
  "calendar.schedulingIntelligence":"ذكاء جدولة المحتوى",
  "calendar.scheduleMissingDates":"جدولة العناصر غير المؤرخة",
  "calendar.itemsNeedDates":"عناصر تحتاج إلى تاريخ نشر",
  "calendar.optimizeCadence":"تحسين وتيرة النشر",
  "calendar.optimizeCadenceDescription":"وزع المحتوى لتجنب التزاحم وفترات التوقف.",
  "calendar.balancePlatforms":"موازنة توزيع المنصات",
  "calendar.dominantPlatform":"المنصة الأكثر استخدامًا",
  "calendar.bestPublishingTime":"اقتراح أفضل وقت للنشر",
  "calendar.bestPublishingTimeDescription":"استخدم تحليلات الجمهور لاختيار نافذة النشر المثالية.",

  "aiStudio.workspace":"استوديو الذكاء الاصطناعي",
  "aiStudio.title":"مركز تشغيل الذكاء الاصطناعي",
  "aiStudio.subtitle":"إدارة الوكلاء الذكيين وسير العمل والمهام والذاكرة والأدوات والموافقات البشرية من مساحة موحدة.",
  "aiStudio.openTemplates":"قوالب الوكلاء",
  "aiStudio.createWorkflow":"إنشاء سير عمل",
  "aiStudio.totalAgents":"إجمالي الوكلاء",
  "aiStudio.currentlyActive":"يعملون حاليًا",
  "aiStudio.runningTasks":"المهام الجارية",
  "aiStudio.liveExecutions":"عمليات تنفيذ مباشرة",
  "aiStudio.pendingApprovals":"الموافقات المعلقة",
  "aiStudio.humanReviewRequired":"تحتاج إلى مراجعة بشرية",
  "aiStudio.systemHealth":"صحة النظام",
  "aiStudio.operational":"يعمل بصورة طبيعية",
  "aiStudio.agents":"الوكلاء الذكيون",
  "aiStudio.digitalOrganization":"المنظمة الرقمية",
  "aiStudio.tasks":"المهام",
  "aiStudio.success":"النجاح",
  "aiStudio.successRate":"نسبة النجاح",
  "aiStudio.model":"النموذج",
  "aiStudio.workflow":"سير العمل",
  "aiStudio.executionPipeline":"مسار التنفيذ",
  "aiStudio.live":"مباشر",
  "aiStudio.taskQueue":"قائمة انتظار المهام",
  "aiStudio.activeExecutions":"عمليات التنفيذ النشطة",
  "aiStudio.humanAuthority":"السلطة البشرية النهائية",
  "aiStudio.approvalCenter":"مركز الموافقات",
  "aiStudio.noApprovals":"لا توجد موافقات معلقة",
  "aiStudio.noApprovalsDescription":"جميع القرارات المطلوبة تمت مراجعتها.",
  "aiStudio.approve":"موافقة",
  "aiStudio.reject":"رفض",
  "aiStudio.controlPlane":"طبقة التحكم",
  "aiStudio.runtimeResources":"موارد تشغيل الذكاء الاصطناعي",
  "aiStudio.modelRouter":"موجّه النماذج",
  "aiStudio.connectedModels":"نماذج متصلة",
  "aiStudio.costMonitor":"مراقبة التكلفة",
  "aiStudio.todayUsage":"استخدام اليوم",
  "aiStudio.memory":"الذاكرة والمعرفة",
  "aiStudio.knowledgeSources":"مصادر معرفة",
  "aiStudio.tools":"سجل الأدوات",
  "aiStudio.registeredTools":"أدوات مسجلة",
  "aiStudio.executionLogs":"سجل التنفيذ",
  "aiStudio.liveRuntimeEvents":"أحداث التشغيل المباشرة",
  "aiStudio.agentInspector":"تفاصيل الوكيل",
  "aiStudio.configure":"إعداد الوكيل",
  "aiStudio.openAgent":"فتح الوكيل",
  "aiStudio.status.active":"نشط",
  "aiStudio.status.running":"يعمل",
  "aiStudio.status.idle":"خامل",
  "aiStudio.status.waiting":"ينتظر",
  "aiStudio.status.error":"خطأ",
  "aiStudio.taskStatus.queued":"في الانتظار",
  "aiStudio.taskStatus.running":"قيد التنفيذ",
  "aiStudio.taskStatus.approval":"بانتظار الموافقة",
  "aiStudio.taskStatus.completed":"مكتمل",
  "aiStudio.taskStatus.failed":"فشل",
  "aiStudio.priority.critical":"حرجة",
  "aiStudio.priority.high":"عالية",
  "aiStudio.priority.medium":"متوسطة",
  "aiStudio.priority.low":"منخفضة",
  "aiStudio.risk.high":"مخاطرة عالية",
  "aiStudio.risk.medium":"مخاطرة متوسطة",
  "aiStudio.risk.low":"مخاطرة منخفضة",

  "aiStudio.enterpriseLabel":"CREATOROS AI ENTERPRISE",
  "aiStudio.enterpriseTitle":"نظام تشغيل الوكلاء الذكيين",
  "aiStudio.enterpriseSubtitle":"مركز موحد للإدارة والتنسيق والتصميم والتنفيذ.",
  "aiStudio.enterpriseNavigation":"التنقل داخل استوديو الذكاء الاصطناعي",
  "aiStudio.operationsCenter":"مركز العمليات",
  "aiStudio.operationsCenterDescription":"الوكلاء والمهام والموافقات والمراقبة",
  "aiStudio.workflowDesigner":"مصمم سير العمل",
  "aiStudio.workflowDesignerDescription":"بناء وتشغيل خطوط الوكلاء",
  "aiStudio.runtimeOnline":"محرك الذكاء متصل",
  "aiStudio.enterpriseConnected":"CreatorOS AI Runtime",

  "aiStudio.runtimeWorkspace":"CREATOROS AI RUNTIME",
  "aiStudio.runtimeTitle":"مركز تشغيل الذكاء الاصطناعي",
  "aiStudio.runtimeSubtitle":"عرض حي لجميع الوكلاء والمحركات والنماذج والأدوات المسجلة داخل CreatorOS.",
  "aiStudio.runtimeLoading":"جارٍ الاتصال بمحرك الذكاء الاصطناعي",
  "aiStudio.runtimeLoadingDescription":"يتم الآن تحميل خدمات CreatorOS المسجلة.",
  "aiStudio.runtimeUnavailable":"محرك الذكاء الاصطناعي غير متاح",
  "aiStudio.retry":"إعادة المحاولة",
  "aiStudio.runtimeDegraded":"تشغيل جزئي",
  "aiStudio.refreshRuntime":"تحديث",
  "aiStudio.lastRefreshFailed":"فشل آخر تحديث:",
  "aiStudio.runtimeProviders":"مزودو Runtime",
  "aiStudio.discoveredProviders":"خدمات مكتشفة فعليًا",
  "aiStudio.runtimeCapabilities":"القدرات المتصلة",
  "aiStudio.connectedCapabilities":"أنظمة تشغيل موحدة",
  "aiStudio.workflows":"سير العمل",
  "aiStudio.liveOrchestrators":"محركات تنظيم حية",
  "aiStudio.searchRuntime":"بحث في",
  "aiStudio.noRuntimeProviders":"لا توجد خدمات Runtime مطابقة.",
  "aiStudio.inspect":"فحص",
  "aiStudio.ping":"اختبار الاتصال",
  "aiStudio.dryRun":"تشغيل تجريبي",
  "aiStudio.showLess":"عرض أقل",
  "aiStudio.showAll":"عرض الكل",
  "aiStudio.executionRuntime":"RUNTIME EXECUTIONS",
  "aiStudio.executionHistory":"سجل التنفيذ والاعتمادات",
  "aiStudio.noExecutions":"لا توجد عمليات تنفيذ حتى الآن.",
  "dashboard.aiIntelligence":"ذكاء اصطناعي",
  "dashboard.productionIntelligenceCenter":"مركز ذكاء الإنتاج",
  "dashboard.aiAgents":"وكلاء الذكاء الاصطناعي",
  "dashboard.activeAgents":"النشطون",
  "dashboard.contentPipeline":"مسار المحتوى",
  "dashboard.running":"يعمل",
  "dashboard.productionHealth":"صحة الإنتاج",
  "dashboard.optimal":"مثالي",
  "dashboard.nextActions":"الإجراءات التالية",
  "dashboard.recommendations":"توصيات",
  "dashboard.connected":"متصل",
  "dashboard.activityProject":"مشروع",
  "dashboard.activityScript":"سكربت",
  "dashboard.disconnected":"غير متصل",
  "dashboard.persistent":"تخزين دائم"
};

