import type { TranslationDictionary } from "./types";

export const en: TranslationDictionary = {

  "app.name":"CreatorOS Enterprise",

  "navigation.commandCenter":"Command Center",
  "navigation.intelligence":"Intelligence",

  "navigation.dashboard":"Dashboard",
  "navigation.projects":"Projects",
  "navigation.scripts":"Scripts",
  "navigation.calendar":"Content Calendar",
  "navigation.aiStudio":"AI Content Studio",
  "navigation.prompts":"Prompt Library",

"dashboard.active":"Active",

"dashboard.totalWorkspaces":"Total content workspaces",
"dashboard.scriptsStored":"Scripts stored on the server",
"dashboard.productionAssets":"Production assets",

"dashboard.scheduledContent":"Scheduled Content",
"dashboard.calendarItems":"Publishing calendar items",
"dashboard.calendarPipeline":"Calendar pipeline",

"dashboard.aiPrompts":"AI Prompts",
"dashboard.promptTemplates":"Reusable intelligent templates",
"dashboard.aiWorkspace":"AI workspace",

"dashboard.productionOverview":"Production Overview",
"dashboard.workspaceDistribution":"Workspace distribution",
"dashboard.recentActivity":"Recent Activity",
"dashboard.latestItems":"Latest workspace items",
"dashboard.systemStatus":"System Status",

  "navigation.expand":"Expand navigation",
  "navigation.collapse":"Collapse navigation",
  "navigation.aria":"CreatorOS navigation",
  "navigation.open":"Open navigation",

  "system.operational":"System operational",
  "system.disconnected":"System disconnected",
  "system.connected":"Frontend and backend connected",
  "system.backendUnavailable":"Backend connection unavailable",

  "header.search":"Search CreatorOS...",
  "header.production":"Production",
  "header.refresh":"Refresh dashboard",
  "header.admin":"Workspace Admin",

  "dashboard.title":"CreatorOS Command Center",
  "dashboard.subtitle":"Manage projects, production and AI from one workspace.",

  "actions.newProject":"New Project",
  "actions.newScript":"New Script",
  "actions.schedule":"Schedule Content",
  "actions.newPrompt":"New Prompt",

"quickActions.title":"Quick Actions",
"quickActions.subtitle":"Start creating",

"quickActions.createProject":"Create project",
"quickActions.startWorkspace":"Start a new content workspace",

"quickActions.createScript":"Create script",
"quickActions.addScript":"Add a script to a project",

"quickActions.scheduleContent":"Schedule content",
"quickActions.addPublishDate":"Add a publishing date",

"quickActions.createPrompt":"Create AI prompt",
"quickActions.saveTemplate":"Save an intelligent template",

"dashboard.operationalHealth":"Operational Health",

"dashboard.backendApi":"Backend API",
"dashboard.storage":"Storage",

"dashboard.healthy":"Healthy",
"dashboard.attention":"Attention",
"dashboard.operational":"Operational",

"projects.workspace":"Projects Workspace",
"projects.title":"Content Projects",
"projects.subtitle":"Organize, search and manage all CreatorOS production workspaces from one operational view.",
"projects.total":"Total projects",
"projects.visible":"Visible results",

"projects.search":"Search projects...",
"projects.filterPlatform":"Filter by platform",
"projects.allPlatforms":"All platforms",
"projects.filterStatus":"Filter by status",
"projects.allStatuses":"All statuses",
"projects.table":"Table",
"projects.kanban":"Kanban",

"projects.noProjects":"No projects found",
"projects.adjustFilters":"Adjust the filters or create a new project.",

"projects.project":"Project",
"projects.platform":"Platform",
"projects.status":"Status",
"projects.id":"ID",
"projects.actions":"Actions",

"projects.creatorProject":"CreatorOS project",
"projects.updateStatus":"Update status",
"projects.delete":"Delete",
"projects.update":"Update",
"projects.details":"Project Details",
"projects.deleteProject":"Delete project",

"scripts.workspace":"Scripts Workspace",
"scripts.title":"Production Scripts",
"scripts.subtitle":"Write, review and manage every CreatorOS script from one focused production environment.",
"scripts.total":"Total scripts",
"scripts.availableProjects":"Available projects",

"scripts.library":"Script Library",
"scripts.allScripts":"All scripts",

"scripts.search":"Search scripts...",
"scripts.filterStatus":"Filter scripts by status",
"scripts.allStatuses":"All statuses",

"scripts.noScripts":"No scripts found",
"scripts.changeFilters":"Create a script or change the current filters.",

"scripts.selectToView":"Select a script to view its information.",
"scripts.details":"Script Details",
"scripts.information":"Information",
"scripts.status":"Status",
"scripts.versionHistory":"Version History",
"scripts.currentVersion":"Current version",
"scripts.currentServerVersion":"Current server version",
"scripts.loadedBackend":"Loaded from CreatorOS backend",

  "calendar.workspace":"Content Calendar",
  "calendar.title":"Publishing Operations",
  "calendar.subtitle":"Plan, inspect and organize scheduled CreatorOS content across projects and platforms.",
  "calendar.totalItems":"Total items",
  "calendar.scheduled":"Scheduled",
  "calendar.withoutDate":"Without date",
  "calendar.currentPeriod":"Current period",
  "calendar.today":"Today",
  "calendar.search":"Search scheduled content...",
  "calendar.filterProject":"Filter by project",
  "calendar.allProjects":"All projects",
  "calendar.filterStatus":"Filter by status",
  "calendar.allStatuses":"All statuses",
  "calendar.filterPlatform":"Filter by platform",
  "calendar.allPlatforms":"All platforms",
  "calendar.view.month":"Month",
  "calendar.view.week":"Week",
  "calendar.view.day":"Day",
  "calendar.view.timeline":"Timeline",
  "calendar.scheduleContent":"Schedule Content",
  "calendar.publishingQueue":"Publishing Queue",
  "calendar.upcomingContent":"Upcoming Content",
  "calendar.queueEmpty":"Publishing queue is empty",
  "calendar.queueEmptyDescription":"There is no scheduled content matching the current filters.",
  "calendar.noDate":"No date",
  "calendar.aiSuggestions":"AI Scheduling Suggestions",
  "calendar.schedulingIntelligence":"Scheduling Intelligence",
  "calendar.scheduleMissingDates":"Schedule items without dates",
  "calendar.itemsNeedDates":"items need publishing dates",
  "calendar.optimizeCadence":"Optimize publishing cadence",
  "calendar.optimizeCadenceDescription":"Distribute content to avoid congestion and inactive periods.",
  "calendar.balancePlatforms":"Balance platform distribution",
  "calendar.dominantPlatform":"Most used platform",
  "calendar.bestPublishingTime":"Suggest the best publishing time",
  "calendar.bestPublishingTimeDescription":"Use audience analytics to select the optimal publishing window.",

  "aiStudio.workspace":"AI Studio",
  "aiStudio.title":"AI Operations Center",
  "aiStudio.subtitle":"Manage intelligent agents, workflows, tasks, memory, tools and human approvals from one unified workspace.",
  "aiStudio.openTemplates":"Agent Templates",
  "aiStudio.createWorkflow":"Create Workflow",
  "aiStudio.totalAgents":"Total Agents",
  "aiStudio.currentlyActive":"currently active",
  "aiStudio.runningTasks":"Running Tasks",
  "aiStudio.liveExecutions":"Live executions",
  "aiStudio.pendingApprovals":"Pending Approvals",
  "aiStudio.humanReviewRequired":"Human review required",
  "aiStudio.systemHealth":"System Health",
  "aiStudio.operational":"Operating normally",
  "aiStudio.agents":"AI Agents",
  "aiStudio.digitalOrganization":"Digital Organization",
  "aiStudio.tasks":"Tasks",
  "aiStudio.success":"Success",
  "aiStudio.successRate":"Success rate",
  "aiStudio.model":"Model",
  "aiStudio.workflow":"Workflow",
  "aiStudio.executionPipeline":"Execution Pipeline",
  "aiStudio.live":"Live",
  "aiStudio.taskQueue":"Task Queue",
  "aiStudio.activeExecutions":"Active Executions",
  "aiStudio.humanAuthority":"Human Final Authority",
  "aiStudio.approvalCenter":"Approval Center",
  "aiStudio.noApprovals":"No pending approvals",
  "aiStudio.noApprovalsDescription":"All required decisions have been reviewed.",
  "aiStudio.approve":"Approve",
  "aiStudio.reject":"Reject",
  "aiStudio.controlPlane":"Control Plane",
  "aiStudio.runtimeResources":"AI Runtime Resources",
  "aiStudio.modelRouter":"Model Router",
  "aiStudio.connectedModels":"Connected models",
  "aiStudio.costMonitor":"Cost Monitor",
  "aiStudio.todayUsage":"Today's usage",
  "aiStudio.memory":"Memory and Knowledge",
  "aiStudio.knowledgeSources":"Knowledge sources",
  "aiStudio.tools":"Tool Registry",
  "aiStudio.registeredTools":"Registered tools",
  "aiStudio.executionLogs":"Execution Logs",
  "aiStudio.liveRuntimeEvents":"Live Runtime Events",
  "aiStudio.agentInspector":"Agent Inspector",
  "aiStudio.configure":"Configure Agent",
  "aiStudio.openAgent":"Open Agent",
  "aiStudio.status.active":"Active",
  "aiStudio.status.running":"Running",
  "aiStudio.status.idle":"Idle",
  "aiStudio.status.waiting":"Waiting",
  "aiStudio.status.error":"Error",
  "aiStudio.taskStatus.queued":"Queued",
  "aiStudio.taskStatus.running":"Running",
  "aiStudio.taskStatus.approval":"Awaiting approval",
  "aiStudio.taskStatus.completed":"Completed",
  "aiStudio.taskStatus.failed":"Failed",
  "aiStudio.priority.critical":"Critical",
  "aiStudio.priority.high":"High",
  "aiStudio.priority.medium":"Medium",
  "aiStudio.priority.low":"Low",
  "aiStudio.risk.high":"High risk",
  "aiStudio.risk.medium":"Medium risk",
  "aiStudio.risk.low":"Low risk",

  "aiStudio.enterpriseLabel":"CREATOROS AI ENTERPRISE",
  "aiStudio.enterpriseTitle":"Intelligent Agent Operating System",
  "aiStudio.enterpriseSubtitle":"A unified center for management, orchestration, design and execution.",
  "aiStudio.enterpriseNavigation":"AI Studio navigation",
  "aiStudio.operationsCenter":"Operations Center",
  "aiStudio.operationsCenterDescription":"Agents, tasks, approvals and monitoring",
  "aiStudio.workflowDesigner":"Workflow Designer",
  "aiStudio.workflowDesignerDescription":"Build and execute agent pipelines",
  "aiStudio.runtimeOnline":"AI Runtime Online",
  "aiStudio.enterpriseConnected":"CreatorOS AI Runtime"

};

