export const REDIS_CLUSTER_OPTIONS =
  Symbol('REDIS_CLUSTER_OPTIONS');

export const REDIS_CLUSTER_CONNECTION =
  Symbol('REDIS_CLUSTER_CONNECTION');

export const REDIS_CLUSTER_STORE_CLIENT =
  Symbol('REDIS_CLUSTER_STORE_CLIENT');

export const REDIS_CLUSTER_NAMESPACE =
  Symbol('REDIS_CLUSTER_NAMESPACE');

export const REDIS_CLUSTER_KEY_FACTORY =
  Symbol('REDIS_CLUSTER_KEY_FACTORY');
