import { Injectable } from '@nestjs/common';
import {
  IntelligenceGenerateRequest,
  IntelligenceGenerateResult,
  IntelligenceProvider,
} from '../interfaces/intelligence-provider.interface';

@Injectable()
export class MockIntelligenceProvider implements IntelligenceProvider {
  readonly name = 'mock' as const;

  async isAvailable(): Promise<boolean> {
    return true;
  }

  async generate(
    request: IntelligenceGenerateRequest,
  ): Promise<IntelligenceGenerateResult> {
    return {
      success: true,
      provider: this.name,
      model: 'creatoros-mock-v1',
      content:
        `[MOCK RESULT]\n` +
        `CreatorOS received the following request:\n${request.prompt}`,
      usage: {
        inputTokens: 0,
        outputTokens: 0,
        totalTokens: 0,
        estimatedCostUsd: 0,
      },
      durationMs: 0,
      fallbackUsed: false,
      warnings: [
        'This result was generated by the mock provider and is not real AI output.',
      ],
    };
  }
}
