import { EnvironmentToolAdapterOptions } from './environment-tool.adapter';

export const PRODUCTION_TOOL_CATALOG: EnvironmentToolAdapterOptions[] = [
  {
    id: 'creatoros-local-ai',
    displayName: 'CreatorOS Local AI (Ollama)',
    capabilities: ['idea-generation', 'research', 'script-generation'],
    mode: 'local',
    costTier: 'free',
    qualityScore: 72,
    enabledEnv: 'OLLAMA_ENABLED',
    configuredByDefault: true,
    enabledByDefault: true,
  },
  {
    id: 'chatgpt',
    displayName: 'ChatGPT',
    capabilities: ['idea-generation', 'research', 'script-generation'],
    mode: 'api',
    costTier: 'medium',
    qualityScore: 94,
    enabledEnv: 'PRODUCTION_TOOL_CHATGPT_ENABLED',
    configuredEnv: 'OPENAI_API_KEY',
  },
  {
    id: 'gemini',
    displayName: 'Google AI Studio (Gemini)',
    capabilities: ['idea-generation', 'research', 'script-generation'],
    mode: 'api',
    costTier: 'free',
    qualityScore: 88,
    enabledEnv: 'PRODUCTION_TOOL_GEMINI_ENABLED',
    configuredEnv: 'GEMINI_API_KEY',
  },
  {
    id: 'hailuo',
    displayName: 'Hailuo AI',
    capabilities: ['video-generation'],
    mode: 'api',
    costTier: 'medium',
    qualityScore: 88,
    enabledEnv: 'PRODUCTION_TOOL_HAILUO_ENABLED',
    configuredEnv: 'HAILUO_API_KEY',
  },
  {
    id: 'capcut-desktop',
    displayName: 'CapCut Desktop',
    capabilities: ['video-editing'],
    mode: 'desktop',
    costTier: 'free',
    qualityScore: 84,
    enabledEnv: 'PRODUCTION_TOOL_CAPCUT_ENABLED',
  },
  {
    id: 'adobe-photoshop',
    displayName: 'Adobe Photoshop',
    capabilities: ['thumbnail-generation', 'thumbnail-editing'],
    mode: 'desktop',
    costTier: 'medium',
    qualityScore: 96,
    enabledEnv: 'PRODUCTION_TOOL_PHOTOSHOP_ENABLED',
  },
  {
    id: 'elevenlabs',
    displayName: 'ElevenLabs',
    capabilities: ['voice-generation'],
    mode: 'api',
    costTier: 'low',
    qualityScore: 95,
    enabledEnv: 'PRODUCTION_TOOL_ELEVENLABS_ENABLED',
    configuredEnv: 'ELEVENLABS_API_KEY',
  },
  {
    id: 'suno',
    displayName: 'Suno AI',
    capabilities: ['music-generation'],
    mode: 'manual-assisted',
    costTier: 'low',
    qualityScore: 88,
    enabledEnv: 'PRODUCTION_TOOL_SUNO_ENABLED',
  },
  {
    id: 'youtube-studio',
    displayName: 'YouTube Studio',
    capabilities: ['publishing-youtube', 'analytics-youtube'],
    mode: 'connector',
    costTier: 'free',
    qualityScore: 94,
    enabledEnv: 'PRODUCTION_TOOL_YOUTUBE_ENABLED',
    configuredEnv: 'YOUTUBE_INTEGRATION_CONFIGURED',
  },
  {
    id: 'tiktok-studio',
    displayName: 'TikTok Studio',
    capabilities: ['publishing-tiktok', 'analytics-tiktok'],
    mode: 'connector',
    costTier: 'free',
    qualityScore: 92,
    enabledEnv: 'PRODUCTION_TOOL_TIKTOK_ENABLED',
    configuredEnv: 'TIKTOK_INTEGRATION_CONFIGURED',
  },
  {
    id: 'manual-local',
    displayName: 'Manual Local Workflow',
    capabilities: [
      'video-generation',
      'thumbnail-generation',
      'thumbnail-editing',
      'voice-generation',
      'music-generation',
      'video-editing',
      'publishing-youtube',
      'publishing-tiktok',
      'analytics-youtube',
      'analytics-tiktok',
    ],
    mode: 'manual-assisted',
    costTier: 'free',
    qualityScore: 55,
    enabledByDefault: true,
    configuredByDefault: true,
  },
];