export const QUEUE_INFRASTRUCTURE_CONFIGURATION =
  Symbol('QUEUE_INFRASTRUCTURE_CONFIGURATION');

export const QUEUE_PROVIDER =
  Symbol('QUEUE_PROVIDER');

export const QUEUE_WORKER_PROVIDER =
  Symbol('QUEUE_WORKER_PROVIDER');

export const QUEUE_HEALTH_PROVIDER =
  Symbol('QUEUE_HEALTH_PROVIDER');

export const QUEUE_WORKER_REGISTRY =
  Symbol('QUEUE_WORKER_REGISTRY');
